create table if not exists public.fixture_partidos (
    id bigint generated by default as identity primary key,
    temporada integer not null,
    fecha_partido timestamptz not null,
    rival text not null,
    condicion text not null check (condicion in ('local', 'visitante')),
    torneo text,
    estado text not null default 'programado' check (estado in ('programado', 'jugado', 'suspendido', 'postergado')),
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists fixture_partidos_fecha_partido_idx
    on public.fixture_partidos (fecha_partido);

create index if not exists fixture_partidos_temporada_fecha_idx
    on public.fixture_partidos (temporada, fecha_partido);

alter table public.fixture_partidos enable row level security;

drop policy if exists "fixture_partidos_public_read" on public.fixture_partidos;
drop policy if exists "fixture_partidos_service_role_all" on public.fixture_partidos;

create policy "fixture_partidos_public_read"
    on public.fixture_partidos
    for select
    to anon, authenticated
    using (true);

create policy "fixture_partidos_service_role_all"
    on public.fixture_partidos
    for all
    to service_role
    using (true)
    with check (true);
